name: run_tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install library
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[d]"
      - name: Run pytest
        run: |
          python -m pytest --cov=pitchtypes --cov-report=xml --cov-report=html --junitxml=junit/test-results.xml
          bash <(curl -s https://codecov.io/bash -t 56557496-4b66-488c-a161-abeb7829823c)
